app:
  appId: wx5a888f089cae16a0
  secret: e4ed40a9b2538eb2d8b725485a6ed22c


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: GMT+8
  profiles:
#    部署的时候记得修改这里
    active: dev
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
